### PR TITLE
Fixes #160: Add pips to tiles

### LINKED ISSUE #160: pips/dots for numbers in UI
Would be helpful to have the dots for the numbers in the UI so you can easily tell which are the higher probability rolls

### PR DESCRIPTION
**Pull request by pachewise**
Adds pips to the relevant tiles using the '•' character, and a helper to map from the Number on the tile to the number of pips.

Opening this for review but haven't really tested it locally yet.

### CODE REVIEW

**Comment by bcollazo** [comment]
Hey! This looks good! Can we:

- Change to `font-size: 100%;` in the `.hexagon` class?
- Add a media query to make the following changes in mobile?
```
@import "../variables.scss";

@media (max-width: $sm-breakpoint) {
  .hexagon {
    --scale-factor: 0.65;
    font-size: 75%;
  }
}
```
- Can we remove the hexagon `clip-path` rule? I was going for a chip-like square hehe.

Like the "pushing to css" the `--scale-factor` and `--base-size` ideas. Thanks!

With these three changes its good to merge! 💪 🚀

**Comment by pachewise** [comment]
I'll make the CSS changes on sizes/media queries.

> Can we remove the hexagon clip-path rule? I was going for a chip-like square hehe.

Hmm, aren't the chips round? Do you want me to make the Paper component round or just square?

**Comment by pachewise** [comment]
@bcollazo used "ch" unit to try to get to a "square" size that worked for all the different tiles. Curious if you agree with this approach or if you have an alternative suggestion. [ch should be usable in most modern-browsers.](https://caniuse.com/ch-unit)

Regular:
Screen Shot 2022-09-12 at 00 32 20


Sm-breakpoint: 

Screen Shot 2022-09-12 at 00 31 25

**Review by bcollazo — APPROVED** [review]
Nice! This looks really good! Thanks for the contribution! 🚀 🚀

**Pull request merged**
