### PR TITLE
add canceling for road building

### PR DESCRIPTION
**Pull request by zuhijan**
HI, I created toggle for Road Building conditional and fixed https://github.com/bcollazo/catanatron/issues/277

### CODE REVIEW

**Review by zarns — CHANGES_REQUESTED** [review]
Just tried this out locally and it works! I think we can do the same change for building settlements/cities as well if you're up to it. Can you remove docker.sock from the PR?

**Comment by zuhijan** [comment]
> Just tried this out locally and it works! I think we can do the same change for building settlements/cities as well if you're up to it. Can you remove docker.sock from the PR?

Yes, I can do it for settlements/cities. Shoud I do it at the same PR? 
I removed docker.sock

p.s. If there are any more frontend tasks, I’d be happy to take them on. I’ve just returned from a sabbatical and would like to brush up on writing code through some simpler tasks.

**Comment by zuhijan** [comment]
@bcollaz any feedback here?

**Comment by bcollazo** [comment]
Hey, thanks @zuhijan for opening the PR and @zarns for taking a look at it. 💪

I haven't had time to review but I think I can take a look before next Sunday. 👍

**Review by bcollazo — APPROVED** [review]
Hey, this looks great! Thanks for the contribution. 💪 🔥 🚀

**Pull request merged**
